services:
  postgres:
    image: postgres:15-alpine
    container_name: intern_tracker_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: intern
      POSTGRES_PASSWORD: intern_password
      POSTGRES_DB: intern_tracker
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
